### ISSUE TITLE
[NV-1621] 🐛 Bug Report: Admin UI not deleting templates in production

### ISSUE THREAD

**Issue by JakovGlavac** [novuhq/novu#1312] opened 2022-09-29 10:59 UTC
### 📜 Description

When the user promotes development changes to production. All changes are not promoted correctly. There is some mismatch.

### 👟 Reproduction steps

Create a few notification templates in the development environment
Then promote those changes to production.
After successful promotion, delete one or two templates from development.
Now promote changes again to production.
Deleted templates are still there in prod and non-editable.

### 👍 Expected behavior

It should delete it

### 👎 Actual Behavior with Screenshots

![Screenshot_2022-09-28-11-42-23-395_com android chrome](https://user-images.githubusercontent.com/34971091/193014029-d1f34abc-8c40-4ffa-a687-ad123dd02eb2.jpg)
![Screenshot_2022-09-28-11-42-27-905_com android chrome](https://user-images.githubusercontent.com/34971091/193014034-386ead71-fc1d-497b-9bd3-63a30c7e77b9.jpg)

### 💻 Operating system

Windows

### 🤖 Node Version

12

### 📃 Provide any additional context for the Bug.

@scopsy fix it by deleting it manually from backend. (if anyone has the same issue)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1621](https://linear.app/novu/issue/NV-1621/🐛-bug-report-admin-ui-not-deleting-templates-in-production)</sub>

**Comment by oba2311** [comment] 2022-10-02 12:23
Let's assign to @JakovGlavac

**Comment by akarsh-jain-790** [comment] 2022-10-14 14:46
@JakovGlavac are you still working? If not @oba2311 can u assign this issue to me ?

**Comment by JakovGlavac** [comment] 2022-10-14 16:24
Sure assign @akarsh-jain-790

**Comment by scopsy** [comment] 2022-12-16 15:23
Hi @akarsh-jain-790 this one is quite critical, so will un-assign you for now due to no progress 🙏

**Comment by LetItRock** [comment] 2022-12-17 21:47
hey, @scopsy @jainpawan21 👋 
I've tried to reproduce the issue here on the `next` branch but without the success. It works for me 😄 🤷‍♂️ 
Could you confirm?

**Comment by scopsy** [comment] 2022-12-18 08:40
Perhaps it was fixed, maybe worth doing a quick check on main branch if it's still there or maybe we are not doing a good reproduced steps.

**Comment by NarHakobyan** [comment] 2022-12-19 07:57
@scopsy Is it possible to delete a workflow that is stuck in production, but doesn't exist in development?

**Comment by scopsy** [comment] 2022-12-19 07:59
@NarHakobyan at this point only from the DB unfortunately. Are you using cloud or self hosting?

**Comment by NarHakobyan** [comment] 2022-12-19 08:01
I'm using cloud, it would be nice to sync current development changes with production 🙏

**Comment by scopsy** [comment] 2022-12-19 08:09
@NarHakobyan do you mind sending a message on intercom and providing there the template id's you want to hide from prod? would love to assist there 🚀

**Comment by NarHakobyan** [comment] 2022-12-19 08:17
@scopsy Sure 🙌

**Comment by scopsy** [comment] 2023-02-01 08:49
@LetItRock seems like this one happening after removing a template and creating a someone with the same id. What I'm thinking is that the "change" generated is not removed when this happens and than a user promotes 2 changes one for the deleted template and another one of the new one

**Comment by LetItRock** [comment] 2023-02-01 21:36
@scopsy ok, I'll investigate this one after finishing other priorities ;)

**Comment by ainouzgali** [comment] 2023-02-05 11:19
I was not able to reproduce it. @scopsy Did you manage to reproduce?

**Comment by scopsy** [comment] 2023-02-05 16:51
@ainouzgali not personally, but I think it might be around what @spakanati has written. Did you tried it with a deleted template with the same identifier?

**Comment by ainouzgali** [comment] 2023-02-05 17:29
Yes, but I might be missing something

**Comment by ainouzgali** [comment] 2023-02-06 10:43
I think it's just that both Pawel and I are working on something else at the moment. So, let's keep it unassigned in case someone else will be able to give it a go. 

I wouldn't cancel it. I wasn't able to reproduce, but there are a lot of recurring complaints about the delete+prod. This should be looked into more thoroughly.

**Closed** 2023-02-09 13:26 UTC
Labels: Assigned & In-Progress, linear, High priority
