### ISSUE TITLE
[NV-211] Default redirect to templates

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2204] opened 2022-12-05 16:35 UTC
## Why?

Currently when visiting the main page "http://localhost:4200/" the page shows an empty page. This should fallback the redirect to "/templates". 

### How?

Create a fallback redirect in react-router under the `apps/web` project to further prevent this from happening we can create a new cypress test to validate this behaviour.

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-211](https://linear.app/novu/issue/NV-211/default-redirect-to-templates)</sub>

**Comment by jainpawan21** [comment] 2022-12-05 18:17
Duplicate of https://github.com/novuhq/novu/issues/377

**Closed by jainpawan21** 2022-12-05 18:17 UTC
