### ISSUE TITLE
[NV-1244] 🐛 Bug Report: UI making requests to localhost when deployed on remote server

### ISSUE THREAD

**Issue by SpencerMiller23** [novuhq/novu#1255] opened 2022-09-13 15:27 UTC
### 📜 Description

The first issue is that the console hangs on the line reading `Attaching to ws, api, web, widget, embed`. In addition, when trying to sign up, I get a message reading "Network error".

### 👟 Reproduction steps

1. Setup a new remote server with the appropriate SSH keys (I'm using Digital Ocean)
2. Create a docker context for the remote server and change the current context to use it
3. Run `docker-compose up`
4. Note: I also changed all the variables in the .env file to use the IP of my server and the problem persisted

### 👍 Expected behavior

Start all the containers on the remote server

### 👎 Actual Behavior with Screenshots

I checked the Network tab of Chrome dev tools and I can see that the requests are being made to localhost and not my IP (even after updating the URLs in the .env file.

![1](https://user-images.githubusercontent.com/18691235/189942556-5407e209-1498-44de-bb0a-2d338667a784.png)
![2](https://user-images.githubusercontent.com/18691235/189942565-7c17c469-c601-4cc8-9c9a-36a24092b912.png)

### 💻 Operating system

Linux

### 🤖 Node Version

v16.14.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1244](https://linear.app/novu/issue/NV-1244/🐛-bug-report-ui-making-requests-to-localhost-when-deployed-on-remote)</sub>

**Comment by SpencerMiller23** [comment] 2022-09-29 06:06
Hey, @djabarovgeorge thanks for getting back to me. I can confirm both that the .env file is located in the same directory as the docker-compose.yml file and that hosting the docker environment locally works as expected.

**Comment by djabarovgeorge** [comment] 2022-09-29 08:05
Hey thanks for looking it up.
Strange the last thing i could suggest checking is to connect to the service and validate if environment variables were updated, however, I am not sure the issue is there. 

@scopsy @davidsoderberg do you have any insights on the matter?

**Comment by techsavvyash** [comment] 2022-10-03 10:06
Hey, I would like to take this up.

**Comment by 3576892** [comment] 2022-10-03 10:09
Em seg, 3 de out de 2022 08:06, Yash Mittal ***@***.***>
escreveu:

**Comment by SpencerMiller23** [comment] 2022-11-07 13:51
Hey @techsavvyash how's it going? Any updates for us?

**Comment by oba2311** [comment] 2022-12-04 21:31
Hi, @iampearceman  coud you help us understand who's working on this? thanks

**Comment by oba2311** [comment] 2022-12-19 09:05
@techsavvyash thanks for your intention - it's been quite some time and we want to get this done and therefore will take this one home and execute soon with the team. Thanks!

**Comment by scopsy** [comment] 2023-01-26 14:22
@SpencerMiller23 tried to replicate this but without a lot of luck, is this is something you encounter? If yes, will do a deep dive with the team about it.

**Comment by scopsy** [comment] 2023-02-05 17:14
I think we found a similiar issue and resolved it as part of 0.11.0, if you could take a look at this again with the new version. Closing this issue for now.

**Closed by scopsy** 2023-02-05 17:14 UTC
Labels: bug, help wanted, linear
