### ISSUE TITLE
🐛 Bug Report: Cancellation API does not cancel triggered events

### ISSUE THREAD

**Issue by iamclaytonray** [novuhq/novu#2937] opened 2023-03-02 17:14 UTC
### 📜 Description

When calling the cancellation API, I get a successful response but the triggered event is not cancelled.

### 👟 Reproduction steps

1. Create an event
2. Grab the transactionId from that triggered event
3. Call the cancellation API to cancel that triggered event ([API Reference](https://docs.novu.co/api/cancel-triggered-event/))

After completing those steps, you should get a successful response, however, you'll see that the event is not actually cancelled

### 👍 Expected behavior

The cancelled event should be cancelled

### 👎 Actual Behavior with Screenshots

I'm happy to share screenshots privately.

### 📃 Provide any additional context for the Bug.

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1802](https://linear.app/novu/issue/NV-1802/🐛-bug-report)</sub>

**Comment by oba2311** [comment] 2023-03-05 21:28
@scopsy  moving this one to tech triage to make sure this bug indeed exist - seems to me mid-high prio.  Unless you understand something I"ve missed than would be good to take care during the cycle.

**Comment by ainouzgali** [comment] 2023-03-06 09:53
Hi @iamclaytonray! Thanks for reporting! 
The screenshot will be very helpful to help us reproduce and get to the bottom of this. 
My email is gali@novu.co or on discord Gali Ainouz#2106 . Will be very happy to help!

**Comment by scopsy** [comment] 2023-03-07 09:52
@iamclaytonray to add to what Gali has mentioned, could you provide some information regarding your workflow? What steps do you have? Do you have a delay/digest running? Might it be that the notification was already processed before you called the cancelation API? Or did you had a long enough delay to be able to cancel it fasy?

**Comment by iamclaytonray** [comment] 2023-03-08 18:02
Sorry for the delay. I'm emailing @ainouzgali now.

I know that the delayed job was very well into the future (in some cases, 7+ days out). We are currently only cancelling delayed jobs. I'll actually try do a screen recording to show the full behavior and send to @ainouzgali

**Comment by ainouzgali** [comment] 2023-03-10 10:23
Hi @iamclaytonray ! Got your recording, very detailed, thanks!
From first glance, it does look like a bug and quite odd behavior. We will need to do some investigating. 

Also, we seem to not show any canceled indications in the activity feed , even when they are actually canceled they appear the same - I will open a separate ticket on that. Very important and a miss on our part.  

I will keep you updated :)

**Comment by iamclaytonray** [comment] 2023-03-14 14:38
Thanks! Wanted to check-in. Is there anything else I can do to help support? 🙂

**Comment by uannight** [comment] 2023-03-15 14:25
I think that I have the same problem.

- Add a new notification with delay including payload field sendAt.
- Send a trigger with this body `{"name":"notification","to":"32345433","payload":{"sendAt":"2023-03-15T14:22:13.298Z"}}`
- Receive a response like that `{"data":{"acknowledged":true,"status":"processed","transactionId":"75a7b0d7-dde7-421b-9b17-b5cf40272dfa"}}`
- Send a cancel operation including the transaction id returned. ` http://localhost:3000/v1/events/triggers/75a7b0d7-dde7-421b-9b17-b5cf40272dfa`
- The response is 404 Not Found

**Comment by scopsy** [comment] 2023-03-19 17:47
Thank you @uannight for the information will review this soon :)

**Comment by ainouzgali** [comment] 2023-03-22 11:11
Hi @uannight could you please try with `http://localhost:3000/v1/events/trigger/75a7b0d7-dde7-421b-9b17-b5cf40272dfa`
Change triggers -> trigger. That at least should not get the 404 error 

@iamclaytonray, I have not been able to reproduce yet. Let me try a few more things and I'll update here what I find.

**Comment by ainouzgali** [comment] 2023-03-22 11:56
@iamclaytonray sorry, I wasn't able to reproduce. It works for me and actually canceled the notification with multiple delayed variations (But, do notice - it did not remove from the activity feed, so we do have to add some indication of canceled to that) 

On your video, you got the payload {"data": false } and it should return true if cancel was successful. But that could be because you are printing res from the axios request which comes after you do the novu.cancel. Could you please also print the result from the cancel on line 29? Let's see if that also returns false. 

If novu.cancel returns {"data": true }, could you please also send me screenshots of activity feed before you trigger the cancel and also after the delayed time elapses? 

Lets see what comes up, and then maybe, if you'd like, jump on a call to figure it out.

**Comment by uannight** [comment] 2023-03-22 14:42
Thank you @ainouzgali with the right url is working right. Sorry for the inconvenience, I'm used to urls being plural. That was my mistake.

**Comment by scopsy** [comment] 2023-03-27 16:50
@iamclaytonray are you still able to reproduce this on the managed service? We are not able to reproduce this behavior internally. Let me know if we can close this one 🙏

**Comment by ainouzgali** [comment] 2023-04-03 13:14
@iamclaytonray I will close it for now, as we did not get your response for a while and were not able to reproduce.  But, do feel free to reach out if you still experience this. Thanks!

**Closed by ainouzgali** 2023-04-03 13:14 UTC
Labels: linear, triage

**Comment by iamclaytonray** [comment] 2023-04-03 14:21
Sorry, I've been super busy. To me, there are two issues.

1. The bug I mentioned. I'll try to repro again.
2. The UI now showing a cancelled state. Is this one fixed?

**Comment by ainouzgali** [comment] 2023-04-03 14:48
@iamclaytonray the ui indication is in the work plan for next month. 
About 1 - let us know :)
