### ISSUE TITLE
[NV-1237] Docs - gettig started , change "Navigate" / reactRouter

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#2104] opened 2022-11-27 11:49 UTC
He would prefer to have the gettig started docs as a stand-alone i.e. with as little help from other libraries as possigle.

we coud replace the `Navigate` with:

```
window.location.href = 
```

---

Created via [Raycast](https://www.raycast.com)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1237](https://linear.app/novu/issue/NV-1237/docs-gettig-started-change-navigate-reactrouter)</sub>

**Comment by scopsy** [comment] 2022-12-01 11:13
@oba2311 lacking a bit of context for this issue. Could you elaborate a bit please?

**Comment by jainpawan21** [comment] 2022-12-11 01:00
Similar to https://github.com/novuhq/novu/issues/2056

**Comment by p-fernandez** [comment] 2023-03-08 11:24
Seems like a duplicate of what @jainpawan21 is pointing. As it is fixed there, closing. Feel free to reopen if needed @oba2311.

**Closed by p-fernandez** 2023-03-08 11:24 UTC
