### ISSUE TITLE
[NV-2945] 🚀 Feature: Add Bulksms SMS provider

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu#4343] opened 2023-10-03 01:20 UTC
### 🔖 Feature description

Use the [Bulksms docs](https://www.bulksms.com/developer/json/v1/#tag/Message%2Fpaths%2F~1messages%2Fpost) to implement a new sms provider while following the [Novu new provider guide](https://docs.novu.co/community/add-a-new-provider#how-to-add-a-new-provider)

### 🎤 Why is this feature needed ?

To have more providers for the community to use

### ✌️ How do you aim to achieve this?

Community contribution

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-2945](https://linear.app/novu/issue/NV-2945/🚀-feature-add-bulksms-sms-provider)</sub>

**Comment by shaikahmadnawaz** [comment] 2023-10-03 01:45
I will work on this issue.

**Comment by pragyamishra56** [comment] 2023-10-03 03:27
could you please asssign me ?

**Comment by fadkeabhi** [comment] 2023-10-03 05:02
As this issue is still not assigned to anyone, I would like to work on this issue. I have already read the documentation of Bulksms, And I will be glad to work with it.

**Comment by pragyamishra56** [comment] 2023-10-03 05:21
Hi @fadkeabhi, please allow me to assign myself to this issue. This will be my first contribution.

**Comment by unicodeveloper** [comment] 2023-10-03 06:19
@shaikahmadnawaz you have been assigned to this issue.

**Comment by pragyamishra56** [comment] 2023-10-03 06:33
please assign to me I'll work on this issue

**Comment by LetItRock** [comment] 2023-10-03 12:19
> I will work on this issue.

hey @shaikahmadnawaz please finish the other ticket that you are already assigned to 🙏

**Comment by LetItRock** [comment] 2023-10-03 12:21
> As this issue is still not assigned to anyone, I would like to work on this issue. I have already read the documentation of Bulksms, And I will be glad to work with it.

hey @fadkeabhi! we would like to be fair with everyone :) if the author won't be able to deliver the solution we will ping you, hope that it works :)

**Comment by pragyamishra56** [comment] 2023-10-03 12:23
hey please assign me issue

**Comment by pragyamishra56** [comment] 2023-10-03 12:24
sorry for late reply could you please assign this issue

**Comment by fadkeabhi** [comment] 2023-10-03 12:26
> sorry for late reply could you please assign this issue

Hey @pragyamishra56 this issue is already assigned to you. You can see it in Assignees section.

**Comment by pragyamishra56** [comment] 2023-10-03 12:50
could you provide me with more details so that i can resolve this issues

**Comment by nick2432** [comment] 2023-10-03 13:07
can work on this?

**Comment by weedertree** [comment] 2023-10-03 16:54
hey, could you please assign me with this issue

**Comment by Yash-sudo-web** [comment] 2023-10-05 17:18
Heyy @pragyamishra56 are you still working on this issue? if not @LetItRock can you please assign this issue to me? I'm willing to submit a PR right away

**Comment by parveshsaini** [comment] 2023-10-10 06:09
Hey @Cliftonz @LetItRock @unicodeveloper ! If the current assignee is unable to proceed with this issue, can you please assign it to me?

**Comment by ashanviii** [comment] 2023-10-10 17:46
Hey @Cliftonz if the issue is still not resolved can you please assign it to me !

**Comment by Cliftonz** [comment] 2023-10-11 00:06
@ashanviii Reassigning to you, if we do not see progress within 3 days we will reassign.

**Comment by ashanviii** [comment] 2023-10-12 11:30
@Cliftonz Thanks working on it!!

**Comment by nick2432** [comment] 2023-10-14 00:53
can i work on this?

**Comment by Cliftonz** [comment] 2023-10-17 18:20
Reassigning

**Comment by Cliftonz** [comment] 2023-10-17 18:22
@DarshanBorse feel free to use https://github.com/novuhq/novu/pull/1972 for assistance, but you should follow the novu guide first.

**Comment by HarshJainofficial** [comment] 2023-10-26 17:33
@Cliftonz  could you assign me so that I can contribute

**Comment by ayushshukla7777** [comment] 2023-10-30 19:59
hey @Cliftonz , I would like to raise a PR for this.

**Closed** 2023-10-31 13:11 UTC
Labels: good first issue, Hacktoberfest
