### ISSUE TITLE
🐛 Bug Report: Novu UI is not allowing me to copy API Keys

### ISSUE THREAD

**Issue by HanumanthaRAON** [novuhq/novu#3606] opened 2023-06-16 07:36 UTC
### 📜 Description

We have deployed novu on aws ec2 instance with local mode with Mongodb and redis DB.

The application is up and running but it is not allowing us copy API key , however we have deployed same in local desktop environment it is allowing us to copy API key.

### 👟 Reproduction steps

Download the novu repo and deploy the novu with local mode.

below are env file config:

 cat .env
# Secrets
# YOU MUST CHANGE THESE BEFORE GOING INTO PRODUCTION
JWT_SECRET=your-secret
STORE_ENCRYPTION_KEY="<ENCRYPTION_KEY_MUST_BE_32_LONG>"

# General
NODE_ENV=local
MONGO_URL=XXXXXXXXXXXX
MONGO_MAX_POOL_SIZE=500
REDIS_HOST=XXXXXXXXXX
REDIS_CACHE_SERVICE_HOST=XXXXXXXXXXXXX

# AWS
S3_LOCAL_STACK=http://localhost:4566
S3_BUCKET_NAME=novu-local
S3_REGION=us-east-1
AWS_ACCESS_KEY_ID=test
AWS_SECRET_ACCESS_KEY=test

# Ports
API_PORT=3000
REDIS_PORT=6379
REDIS_CACHE_SERVICE_PORT=6379
WS_PORT=3002

# Root URL
REACT_APP_WS_URL=http://AWSPublicIP:3002
# Uncomment this one when deploying Novu in the local environment
# as Web app local Dockerfile will have to load this to be used.
# Deployment version doesn't need as we inject it with API_ROOT_URL value.
REACT_APP_API_URL=http://AWSPublicip:3000
API_ROOT_URL=http://AWSPublicip:3000
DISABLE_USER_REGISTRATION=false
FRONT_BASE_URL=http://client:4200
WIDGET_EMBED_PATH=http://AWSPublicip:4701/embed.umd.min.js
WIDGET_URL=http://AWSPublicip:4500

# Context Paths
# Only needed for setups with reverse-proxies
GLOBAL_CONTEXT_PATH=
WEB_CONTEXT_PATH=
API_CONTEXT_PATH=
WS_CONTEXT_PATH=
WIDGET_CONTEXT_PATH=

# Analytics
SENTRY_DSN=
NEW_RELIC_APP_NAME=
NEW_RELIC_LICENSE_KEY=

after updating env with above running 

docker-compose up -d from same direcotry where compose and env files exist

### 👍 Expected behavior

We should be able copy the API Key

### 👎 Actual Behavior with Screenshots

![image](https://github.com/novuhq/novu/assets/20111534/10cf9002-c213-44e0-a233-6c6059ed7de9)

Copy option is graded out

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by davidsoderberg** [comment] 2023-06-16 10:07
Hi @HanumanthaRAON, are you running locally on http or https?

**Comment by HanumanthaRAON** [comment] 2023-06-16 10:16
both we are running on http

**Comment by p-fernandez** [comment] 2023-06-16 11:36
Which version are you using @HanumanthaRAON? In the latest version we have deployed in our Cloud service I can't reproduce the error.

**Comment by HanumanthaRAON** [comment] 2023-06-16 11:44
We are using latest version 0.15.0

**Comment by p-fernandez** [comment] 2023-06-16 14:34
Latest version is 0.16.0 for your interest.
I tried to reproduce this bug in the version you are using and the copy button works in both the theme settings and in different browsers.
Which browser are you using? Also could you inspect your Dev Tools console and see if any error is happening there? 🙏🏻

**Comment by HanumanthaRAON** [comment] 2023-06-18 14:31
I see some errors in developer console , please check and help us to resolve it.

![image](https://github.com/novuhq/novu/assets/20111534/1b05162a-a8e2-4920-a041-ecb3f62e6ae9)

**Comment by davidsoderberg** [comment] 2023-06-19 02:49
@HanumanthaRAON the copy function do not work with http and this is a limit for the clipboard api in Javascript. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#writing_to_the_clipboard

**Comment by HanumanthaRAON** [comment] 2023-06-19 05:34
Hi David.

After enabling https now we are getting CORS error.

![image](https://github.com/novuhq/novu/assets/20111534/e0447112-0d48-43ad-b39a-fd6393f6ab7b)

this is the same issue we are getting when deploy same in Kubernetes , can you please check and help us resolve it.

**Comment by p-fernandez** [comment] 2023-06-19 10:43
Closing this as the original issue is explained. Let's merge the CORS problem this discussion in this other issue open: https://github.com/novuhq/novu/issues/3602

**Closed by p-fernandez** 2023-06-19 10:43 UTC
Labels: triage
