### ISSUE TITLE
🐛 Bug Report: notification center attempts to include child_process, fs, etc.

### ISSUE THREAD

**Issue by qw-in** [novuhq/novu#1191] opened 2022-09-03 01:13 UTC
### 📜 Description

```
Module "child_process" has been externalized for browser compatibility. Cannot access "child_process.spawn" in client code.
```

This appears to be due to the reliance on `axios` which does not support esm (or at least known issues with vite).

Ref: https://github.com/vitejs/vite/issues/174, https://github.com/vitejs/vite/issues/184, etc.

Please consider using fetch instead.

### 👟 Reproduction steps

1. Use vite (ts react)
2. `import { NovuProvider } from "@novu/notification-center";`
3. There ya go

### 👍 Expected behavior

Probably want it to work with vite.

### 👎 Actual Behavior with Screenshots

Crashes entire app.

### 💻 Operating system

Linux

### 🤖 Node Version

16

### 📃 Provide any additional context for the Bug.

Technically running via Tauri, but I don't think relevant to the bug

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by AlexVCS** [comment] 2022-09-12 12:16
Hey there, I'd like to work on this issue. Can you assign it to me please?

**Comment by BiswaViraj** [comment] 2022-09-13 07:33
@AlexVCS , I've assigned you 🚀 , let me know if you need any help

**Comment by scopsy** [comment] 2022-11-27 13:17
@AlexVCS did you had a time to look at this? LEt me know if I should un-assign you perhaps someone else will be able to take a look at this 🙏♥️

**Comment by AlexVCS** [comment] 2022-11-28 13:52
Hey @scopsy sorry for the delay! I'd still like to try and work on this, thanks

**Comment by AlexVCS** [comment] 2022-11-28 14:41
I tried recreating this issue. I made a Vite TS React project, installed and included `import { NovuProvider } from "@novu/notification-center";` 

The app seems to run just fine with no crashing or errors. @qw-in are you still having this issue?

**Comment by AlexVCS** [comment] 2022-11-28 14:55
I am on a Mac and not Linux, for the record.

**Comment by scopsy** [comment] 2022-11-29 07:47
@AlexVCS maybe it's only a warning and not an actual error? Perhaps during build time or in the console of the web project?

**Comment by AlexVCS** [comment] 2022-11-29 18:01
Good point @scopsy. From what I've looked at so far it seems like the error occurs during build time.

**Comment by qw-in** [comment] 2022-11-29 23:51
> I tried recreating this issue. I made a Vite TS React project, installed and included `import { NovuProvider } from "@novu/notification-center";`
> 
> The app seems to run just fine with no crashing or errors. @qw-in are you still having this issue?

Unfortunately I am no longer working on the project I was at the time. If no one else can reproduce I'd say probably safe to conclude this issue is fixed. Thanks!

**Comment by Plactom** [comment] 2022-12-13 13:19
It seems that this error keeps happening, but in my tests it only occurred when I put NovuProvider tag. In my case, the error appeared in the console and not in build time!

**Comment by gitstart-novu** [comment] 2023-02-14 12:43
> I tried recreating this issue. I made a Vite TS React project, installed and included `import { NovuProvider } from "@novu/notification-center";`
> 
> The app seems to run just fine with no crashing or errors. @qw-in are you still having this issue?

Same here.

@Plactom could you please state the version of Vite you used. Also it would be helpful to also share your package.json and vite.config.ts along with any additional snippets or info you think might be relevant.

**Comment by gitstart-novu** [comment] 2023-02-16 13:46
@scopsy based on this [comment](https://github.com/vitejs/vite/issues/184#issuecomment-630559146) by one of the Vite maintainers, do you think it's worth it to just go ahead and migrate from using `Axios` to `fetch`?

**Comment by scopsy** [comment] 2023-02-16 14:07
@gitstart-novu would be great if we can use axios for now and just fix the warning.

**Comment by gitstart-novu** [comment] 2023-02-17 13:34
Hi @scopsy still unable to reproduce the issue. Note that it was tried on different versions of `Vite` starting from 2.x.

**Comment by gitstart-novu** [comment] 2023-02-23 11:44
@scopsy Having not been able to reproduce the issue, do you think it's safe to close this issue as fixed?

**Comment by scopsy** [comment] 2023-02-23 14:06
Yes we can close this, can be reopened again if needed 🙏

**Closed by scopsy** 2023-02-23 14:06 UTC
Labels: good first issue, Assigned & In-Progress
