### ISSUE TITLE
[NV-619] Customize empty state - notification center

### ISSUE THREAD

**Issue by ainouzgali** [novuhq/novu#2195] opened 2022-12-05 16:35 UTC
Allow passing an image to the notification center. Similar to users being able to pass stylings or their own notification item/ header.

Currently, we have a default image being displayed in the case of an empty notification list:

![Screen Shot 2022-10-03 at 13.09.17.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/b7827971-57a8-48a7-a2f8-db0962299ea7/9c3e350c-7768-4fb4-a1d9-d556fae6622d)

We would like to allow users of the [notification center ](https://docs.novu.co/notification-center/react-components)react component to customize their own image or component. As a reference, you could look at components that are already customizable by the user- like Header, Footer, or NotificationItem.

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-619](https://linear.app/novu/issue/NV-619/customize-empty-state-notification-center)</sub>

**Comment by ainouzgali** [comment] 2022-12-05 16:35
I, at least, can't think of what else to add

**Comment by ainouzgali** [comment] 2022-12-05 16:35
Looking good. anything missing for this to be released to community? @ainouzgali

**Comment by ainouzgali** [comment] 2022-12-05 16:35
@oba2311 added more words

**Comment by ainouzgali** [comment] 2022-12-05 16:35
@oba2311 We actually don't need Shlomi for this. It is code only. It is basically allowing to pass an image to the notification center. Similar to users being able to pass stylings or their own notification item/ header

**Comment by ainouzgali** [comment] 2022-12-05 16:35
No :) This is to let them change the actual image of no notifications. 905 is that the size of empty notifications and with notifications is not the same.

**Comment by ainouzgali** [comment] 2022-12-05 16:35
Good idea, just need to create something with @shlomtzyk .

**Comment by jainpawan21** [comment] 2022-12-05 17:11
@ainouzgali 
It is duplicate of https://github.com/novuhq/novu/issues/1397 
This PR https://github.com/novuhq/novu/pull/1795 is already merged

**Closed** 2022-12-05 18:15 UTC
