### ISSUE TITLE
🐛 Bug Report: The Integrations Store's add button position is incorrect

### ISSUE THREAD

**Issue by nick2432** [novuhq/novu#4943] opened 2023-12-05 12:50 UTC
### 📜 Description

The position of the integration add button is not correct.
![integration](https://github.com/novuhq/novu/assets/77477551/d41285c5-fb3b-48c1-b062-2c127e47356e)

### 👟 Reproduction steps

Just go to the pages.

### 👍 Expected behavior

Should be aligned.

### 👎 Actual Behavior with Screenshots

See above

### Novu version

Novu SaaS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Dharmavineta** [comment] 2023-12-06 09:28
Hey? What's the status of the issue? Do assign it to me if the issue isn't resolved.

**Comment by jainpawan21** [comment] 2023-12-16 16:34
@nick2432 Are you working on this issue?

**Comment by nick2432** [comment] 2023-12-16 16:44
@jainpawan21 yes

**Closed** 2023-12-18 08:22 UTC
Labels: triage
