### ISSUE TITLE
[NV-1308] [NV-178] Add new provider Matrix (matrix.org)

### ISSUE THREAD

**Issue by iampearceman** [novuhq/novu#2201] opened 2022-12-05 16:35 UTC
| Is your feature request related to a problem? Please [describe.No](http://describe.No) support for Matrix notificationsDescribe the solution you'd likeSupport for itAdditional contexthttps://matrix.org |

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-178](https://linear.app/novu/issue/NV-178/add-new-provider-matrix-matrixorg)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-178](https://linear.app/novu/issue/NV-178/add-new-provider-matrix-matrixorg)</sub>

**Comment by iampearceman** [comment] 2022-12-05 16:35
Sent a message on GitHub issue.

**Comment by jainpawan21** [comment] 2022-12-05 18:19
Duplicate of https://github.com/novuhq/novu/issues/128

**Closed by jainpawan21** 2022-12-05 18:19 UTC
