### ISSUE TITLE
[NV-2929] [NV-2756] When switching the organization the branding information is not refetched

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4232] opened 2023-09-29 15:15 UTC
### Reproduction Steps

1. Navigate to the Brand page, make sure you have logo or font changed from defaults and saved.
2. Change the organization.
3. The branding settings are not updated.

https://github.com/novuhq/novu/assets/2607232/5bd1ecbc-f145-46ed-8049-f3965f4b123d

### Definition of done

* The branding reflects currently selected organisation.
* Display branding related to the selected organisation.

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2756](https://linear.app/novu/issue/NV-2756/when-switching-the-organization-the-branding-information-is-not)</sub>

<sub>[NV-2929](https://linear.app/novu/issue/NV-2929/[nv-2756]-when-switching-the-organization-the-branding-information-is)</sub>

**Comment by SarmadKhoja95** [comment] 2023-10-02 20:46
@LetItRock not able to view/play video.

**Comment by LetItRock** [comment] 2023-10-03 11:16
> @LetItRock not able to view/play video.

@SarmadKhoja95 @shakthi2003-ice thanks, I've just re-uploaded the video ;)

**Comment by SarmadKhoja95** [comment] 2023-10-03 11:19
@LetItRock Can you assign this to me i would like to work on this one?

**Comment by nick2432** [comment] 2023-10-03 13:09
can i work on this?

**Comment by ASCE-D** [comment] 2023-10-03 14:14
Hey Devs I would like to contribute can you please assign me this issue

**Comment by Anonymous961** [comment] 2023-10-03 16:49
@LetItRock can I please try this issue?

**Comment by Anonymous961** [comment] 2023-10-03 19:54
@LetItRock, I've checked the SideNav.tsx, where I found the OrganisationSelect component. Whenever an organisation is selected, the data according to that organisation should be updated. I believe there could be a simple fix by using AuthContext in the BrandingForm page and re-rendering the page every time the organization is changed. Please assign me this issue so that I can work on it with a better approach.

**Comment by 07tAnYa** [comment] 2023-10-04 10:04
Hey! can you assign this to me, I can fix this issue.

**Comment by davidsoderberg** [comment] 2023-10-04 12:31
@SarmadKhoja95 I have now assigned this to you :)

**Comment by SarmadKhoja95** [comment] 2023-10-08 04:08
@davidsoderberg I think its a duplicate of #4297 which is already merged.

**Comment by SarmadKhoja95** [comment] 2023-10-08 04:09
You can close this one so I can work on another one. Thanks !

**Comment by davidsoderberg** [comment] 2023-10-09 05:07
Yes seems like thanks for finding that out :)

**Closed by davidsoderberg** 2023-10-09 05:07 UTC
Labels: bug, good first issue, Hacktoberfest
