### ISSUE TITLE
[NV-1960] 🐛 Bug Report: 

### ISSUE THREAD

**Issue by KlaasVanHoeckROC** [novuhq/novu#3126] opened 2023-04-03 02:22 UTC
### 📜 Description

iFrame integration of the notification center is not responsive. It doesn't adapt it's width to its parent at all

### 👟 Reproduction steps

1. Integrate the iFrame solution with the script.
2. Use Chrome tools to adapt the width of the page dynamically

### 👍 Expected behavior

When the width shrinks, the centre should adapt at least a bit to accommodate more screen sizes

### 👎 Actual Behavior with Screenshots

[](url
<img width="1279" alt="Screenshot 2023-04-03 at 12 21 08" src="https://user-images.githubusercontent.com/114460104/229397219-a861fdf6-26eb-4ac4-b5b0-d12372bc42b8.png">
<img width="1055" alt="Screenshot 2023-04-03 at 12 21 13" src="https://user-images.githubusercontent.com/114460104/229397223-923e2b3b-de7f-427b-a050-f3b87c7baf52.png">
<img width="1800" alt="Screenshot 2023-04-03 at 12 20 45" src="https://user-images.githubusercontent.com/114460104/229397212-a3ff85d8-9dbc-42ab-908f-8c0b89696f33.png">

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1960](https://linear.app/novu/issue/NV-1960/🐛-bug-report)</sub>

**Comment by jainpawan21** [comment] 2023-04-08 13:04
Duplicate of https://github.com/novuhq/novu/issues/3125

**Closed by jainpawan21** 2023-04-08 13:04 UTC
Labels: bug, help wanted, linear
