### ISSUE TITLE
[NV-586] Mark all as read

### ISSUE THREAD

**Issue by ainouzgali** [novuhq/novu#2206] opened 2022-12-05 16:35 UTC
**What this is about:**

In our notification center, we want to indicate when a notification is read or seen. This is the notification center:

![CleanShot 2022-07-28 at 13.55.42@2x.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/a96fbcfc-d495-4b33-9a05-f3158821ca57/b1129687-24e4-4e4c-a2e6-4de37701ab9a)

**Challenge:**

When users receive a large amount of notifications it’s hard to mark all of them manually as seen/read, a common UX behavior is to have a “mark all as seen” functionality. 

**Solution:**

Have a `Mark All as Read` button. Here is the wireframes and design will be added by @shlomtzyk 

**Scope of work and edge cases:**

* When there are no notifications - disable the button.
* This ticket relates to read / unread and read all - seen and not seen are not in scope.
* Update the badge with the correct number of unread.

**Design:**

[Notification Modal - Concepting (Figma)](https://www.figma.com/file/9jalQvImfHtbbExZPLW3XO/Concepting?node-id=2596%3A31923)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-586](https://linear.app/novu/issue/NV-586/mark-all-as-read)</sub>

**Comment by ainouzgali** [comment] 2022-12-05 16:35
@ainouzgali  pls see the design here:  (link to specific frame)

[Notification Modal - Concepting (Figma)](https://www.figma.com/file/9jalQvImfHtbbExZPLW3XO/Concepting?node-id=2596%3A31923)

**Comment by ainouzgali** [comment] 2022-12-05 16:35
Yeah exactly, just didn't understand what you meant by PRD, as it usually refers to a document.

Let's park this on me meanwhile.

**Comment by ainouzgali** [comment] 2022-12-05 16:35
@oba2311 yeah just a well written ticket for it with why, how and where including relevant designs and everything that can help the person trying to solve it.

Let me know if you need help with that if you want to take it from there and I'll add the technical details.

**Comment by ainouzgali** [comment] 2022-12-05 16:35
Cool, @scopsy  can we create a well written ticket?

WDYM by PRD?

**Comment by ainouzgali** [comment] 2022-12-05 16:35
I know we said we don't go back to features. But I feel this is an important one, and sooner the better. 

Maybe community? @oba2311 @scopsy

**Comment by jainpawan21** [comment] 2022-12-05 17:45
Duplicate of https://github.com/novuhq/novu/issues/955

**Closed** 2022-12-05 18:11 UTC
