### ISSUE TITLE
[NV-1210] 🐛 Bug Report: Chat notifications failing (Discord)

### ISSUE THREAD

**Issue by amosbastian** [novuhq/novu#2069] opened 2022-11-22 12:00 UTC
### 📜 Description

I have set up a notification for when someone replies to a comment. It is working fine for in-app notifications, but fails when trying to set a chat notification even though the credentials have been set.

The workflow looks as follows:

![](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/9f562e9c-3b75-4a87-9b9c-12057025b4fa/f33018b3-a02e-4329-9cae-517fc0ba6e4f)

but when testing it, it fails on the chat step

![](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/16f7ee12-a94e-44ef-a08c-302dd01b114b/04c5e978-1965-49e5-ae76-58f035e2cc85)

Note: this is a different error to when the credentials have not been set (see image below), so I believe there is something wrong with the implementation on your side

![](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/3f908019-e426-42bd-8925-d7ceffcd3858/24f879cf-05ef-4c98-b1ea-a89b9b096a5d)

### 👟 Reproduction steps

1. Set credentials with Novu

   ```
   await novu.subscribers.setCredentials(ctx.session.user.id, ChatProviderIdEnum.Discord, {
     webhookUrl: input.discordWebhookUrl,
   });
   ```
2. Trigger workflow test
3. Chat notification fails

### 👍 Expected behavior

It should send a notification to my Discord server

### 👎 Actual Behavior with Screenshots

![](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/16f7ee12-a94e-44ef-a08c-302dd01b114b/04c5e978-1965-49e5-ae76-58f035e2cc85)

### 💻 Operating system

MacOS

### 🤖 Node Version

v18.11.0

### 📃 Provide any additional context for the Bug.

Here is a list of my subscribers

![](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/9c0c85be-d199-4ddc-940d-94236a7a29de/8c64791f-5ca1-4d23-895e-2623853624df)

When I set the credentials with `ctx.session.user.id`, which is `cl76njlpq17133dpaebxdkrqz` in the above image, it fails. When I set it with `633058cf27d50dea0b00a8ce`, it works (which is my Novu account's ID). This leads me to believe it has something to do with the difference between the 2 subscriber accounts, but I'm not sure.

### 👀 Have you spent some time to check if this bug has been raised before?

* [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

* [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

*No response*

> From [SyncLinear.com](https://synclinear.com)

**Comment by LetItRock** [comment] 2023-02-17 11:04
Closing this issue because I wasn't able to reproduce it. I've tried a couple of times for different subscribers.
So I feel like the subscriber with `subscriberId: cl76njlpq17133dpaebxdkrqz` haven't had the credentials set properly (currently it doesn't), or we had an issue somewhere in the code which is now fixed.

![Screenshot 2023-02-17 at 12 01 47](https://user-images.githubusercontent.com/2607232/219630759-ec8580ce-c2a0-4dc5-8257-9b7e4796913d.png)

**Closed by LetItRock** 2023-02-17 11:04 UTC
Labels: bug, help wanted, linear
