### ISSUE TITLE
Email attachment is received empty

### ISSUE THREAD

**Issue by chavda-bhavik** [novuhq/novu#861] opened 2022-07-18 05:47 UTC
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
  - While sending email with attachment, attachment (image) is received with valid size but it's not opening. It looks like image is sent empty. 
  - I test it with `Amazon SES` and `Sendgrid` integrations, same issue with both of them.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
  - While sending larger attachment, I got error with message `Request failed with status code 413`.

- **To reproduce**
  - Here is [repository](https://github.com/chavda-bhavik/attachment-issue). Added two images one (`img/facebook.png`) for empty attachment issue and another one (`img/img-large.jpg`) for 413 error.
  - Put `API_KEY`, `TO_EMAIL` & `TO_PHONE` in `router.js`. 
  - Screenshot of attachment received
![image](https://user-images.githubusercontent.com/50201755/179451199-c7e00617-56e0-483b-901f-32fd1d091db3.png)
  - Notification Template
    ```html
    <p>Hello <b>{{name}}</b></p>
    ```

**Comment by oba2311** [comment] 2022-07-19 08:12
Thanks @chavda-bhavik !
We will look into it this week.

**Comment by davidsoderberg** [comment] 2022-07-20 07:55
@chavda-bhavik are you available to debug this with me? 
Because I get Sendgrid to work with you exampled set up locally?

**Comment by davidsoderberg** [comment] 2022-07-21 05:53
Close this because SES was fixed in https://github.com/novuhq/novu/pull/876 and Sendgrid can't be reproduced

**Closed by davidsoderberg** 2022-07-21 05:53 UTC

**Comment by chavda-bhavik** [comment] 2022-07-22 08:39
Sorry @davidsoderberg for not being able to reply early. Thank you for having a look. 

Did you tried sending large image `img/img-large.jpg`, It's still sending `413 (Request Entity too large)` error. Because of axios i believe.

**Comment by davidsoderberg** [comment] 2022-07-22 08:45
No I did not look into the large attachments could you open a new issue for this?

**Comment by scopsy** [comment] 2022-07-22 08:45
@chavda-bhavik what is the size of the attachment? We currently limit attachments size on the API level aswell.

**Comment by chavda-bhavik** [comment] 2022-07-22 08:46
> @chavda-bhavik what is the size of the attachment? We currently limit attachments size on the API level aswell.

It's `2.6 MB`.
