### ISSUE TITLE
[NV-2696] allow variables in Sender Name field in email editor

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#3958] opened 2023-08-13 11:06 UTC
### What?

We can use variables for the subject, preheader, and content in the email editor

### Why? (Context)

But variables are not working for Sender Name field

![image](https://github.com/novuhq/novu/assets/39362422/d5ed4678-6f54-4d99-a1a8-5bc0d5d8d845)

### Definition of Done

1. Test payload should have by this {{customSenderName}} variable
2. Variables should work with all (almost) email providers

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-2696](https://linear.app/novu/issue/NV-2696/allow-variables-in-sender-name-field-in-email-editor)</sub>

**Comment by gitstart** [comment] 2023-08-14 14:06
@jainpawan21 we would like to pick this up

**Comment by gitstart** [comment] 2023-08-21 09:36
Hi @jainpawan21, we have so far been unable to reproduce this on our end. From the attached screenshots, it looks like the variable being used in the sender's name is being ready by the variable editor and it also reflects on the request payload. Please let us know if there is something we might be missing.

![Screenshot from 2023-08-17 23-23-48](https://github.com/novuhq/novu/assets/1501599/3d7c8132-4fa3-4d76-bc14-1f6f0c3f6e56)
![Screenshot from 2023-08-17 23-24-29](https://github.com/novuhq/novu/assets/1501599/8d9fac9f-7c06-46b5-87a6-0d3aac21e3f2)
![Screenshot from 2023-08-17 23-25-48](https://github.com/novuhq/novu/assets/1501599/66596a8c-b957-4c54-9d51-35e1ec4f8766)

**Comment by scopsy** [comment] 2023-08-21 10:15
@gitstart but have you received and email with the sendername replaced dynamically with the variable in the payload?

**Comment by mahendraHegde** [comment] 2023-09-21 01:04
@scopsy  @jainpawan21  i'm able to reproduce, can you assign this to me? 
I have a question, whats the expectation here, user should be able to add "sender" placeholder data in `payload` section of trigger UI and it should send the email with the sender name correct?
what about the variable editor popup(having value `ayush dura` in the image) is there anything need to be done there?

**Comment by aayushdura** [comment] 2023-09-21 06:37
> @scopsy @jainpawan21 i'm able to reproduce, can you assign this to me? I have a question, whats the expectation here, user should be able to add "sender" placeholder data in `payload` section of trigger UI and it should send the email with the sender name correct? what about the variable editor popup(having value `ayush dura` in the image) is there anything need to be done there?

Yes, we need to able to supply the variable with respective values as the sender name @mahendraHegde .

**Closed** 2023-09-28 07:16 UTC
Labels: help wanted
