### ISSUE TITLE
🐛 Bug Report: Pagination Issue in React component

### ISSUE THREAD

**Issue by singhgulshan** [novuhq/novu#2070] opened 2022-11-22 12:41 UTC
### 📜 Description

Page number not reset to 0 after calling refetch method of`useNotification. 

### 👟 Reproduction steps

Call `fetchNextPage` several times, After that call `refetch` after that again call `fetchNextPage`. Page will be same as old page number.

### 👍 Expected behavior

`refetch` should also reset the page number.

### 👎 Actual Behavior with Screenshots

Calling the last page which was called earlier.
![Screenshot 2022-11-22 at 5 52 49 PM](https://user-images.githubusercontent.com/36273489/203316435-3b90289f-70a1-419b-9bc5-5d34bfffd38f.png)

### 💻 Operating system

MacOS

### 🤖 Node Version

18.6.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by JoaoMagnago** [comment] 2022-12-22 14:34
Hey, @singhgulshan, I could not reproduce that behavior, though whenever I call `refetch`, it does go to page 0. It seems right in most cases, but let's say a user marks a notification as seen in a page different from 0. The `markAsSeen` method is called and the notification box refetches the data so the user can be sure he marked that notification as seen. The issue is that it resets the page to 0 automatically, and I believe that is where the problem is situated.

It would be great if Novu provided a way for us to access a specific page on refetch. Something like this:

```typescript
function refetch({ page: number }) {
  // Refetches on desired page
}
```

**Comment by jainpawan21** [comment] 2023-01-15 19:59
@JoaoMagnago Would you mind to create a feature request for this?

**Comment by JoaoMagnago** [comment] 2023-01-20 14:13
> @JoaoMagnago Would you mind to create a feature request for this?

Hey, @jainpawan21!

Sorry for the delay. I have just created a Feature Request regarding that matter [here](https://github.com/novuhq/novu/issues/2561).

Thank you for the attention and support.

**Comment by scopsy** [comment] 2023-02-05 17:23
Thank you @JoaoMagnago will close this one here in favor of the newly created one.

**Closed by scopsy** 2023-02-05 17:23 UTC
Labels: bug, linear, triage
