### ISSUE TITLE
[NV-769] Add link to docs from the "web" dashboard

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#2203] opened 2022-12-05 16:35 UTC
## Why?

For easier access to documentation of our users.

## How?

Add 2 links fixed on the bottom of the navigation menu with links to:

* Documentation - https://docs.novu.co
* Support - [https://discord.gg/novu](https://discord.gg/novu)

[Deafult picker - Concepting (Figma)](https://www.figma.com/file/9jalQvImfHtbbExZPLW3XO/Concepting?node-id=3274%3A34643)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-769](https://linear.app/novu/issue/NV-769/add-link-to-docs-from-the-web-dashboard)</sub>

**Comment by jainpawan21** [comment] 2022-12-05 18:12
Duplicate of https://github.com/novuhq/novu/issues/1040

**Closed by jainpawan21** 2022-12-05 18:12 UTC
