### ISSUE TITLE
[NV-1197] Add backgroud to the "copy code" button within the code shown in activity feed

### ISSUE THREAD

**Issue by oba2311** [novuhq/novu#2058] opened 2022-11-20 16:29 UTC
See here attached - this is likely to happen in most cases and soe we should fix it:

![CleanShot 2022-11-20 at 18.27.58@2x.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/be9f3422-1ed0-4999-b7fa-4922007b1597/8b34e6e7-b8c0-4aae-a9b6-6d6155e85fba)

---

Created via [Raycast](https://www.raycast.com)

> From [SyncLinear.com](https://synclinear.com)

**Comment by raikasdev** [comment] 2022-11-30 12:15
Cannot reproduce: This seems to have been added by the Mantine team

**Comment by p-fernandez** [comment] 2023-06-15 13:19
Closed as we have a new design implementation for the snippets.

**Closed** 2023-06-15 13:19 UTC
