### ISSUE TITLE
🚀 Feature:  Add WhatsApp single and group messaging

### ISSUE THREAD

**Issue by inglesuniversal** [novuhq/novu#2096] opened 2022-11-25 15:56 UTC
### 🔖 Feature description

A lot of API offer single messaging interaction with WhatsApp. It would be just awesome if you guys can add group based notifications and bulk sending messaging to WhatsApp users.

Regards

### 🎤 Why is this feature needed ?

It would enhance your product and serve a large user dataset

### ✌️ How do you aim to achieve this?

Provide a single API which can allow the end user to connect to his personal contacts

### 🔄️ Additional Information

N/A

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by haikyuu** [comment] 2022-12-31 15:59
Duplicate of #1019

**Comment by p-fernandez** [comment] 2023-06-15 13:20
Closed in favour of https://github.com/novuhq/novu/issues/1019.

**Closed by p-fernandez** 2023-06-15 13:20 UTC
Labels: linear, triage
