### ISSUE TITLE
[NV-1250] 🐛 Bug Report: No counter nor any popup running Safari browsers

### ISSUE THREAD

**Issue by JustinBack** [novuhq/novu#1090] opened 2022-08-20 13:02 UTC
### 📜 Description

On: iOS 16 B4 and iPadOS 16 B3, but also on mac devices running safari. 

See the top right corner (Bell)

Embedded using the JS Method on a self hosted environment running master images.

https://user-images.githubusercontent.com/40178814/185747234-f5b2327e-6cae-414b-b3d3-2621e164606f.MOV

The embed doesn‘t popup nor is there any unread counter (it works on Windows!)

The console doesn‘t log anything either.

### 👟 Reproduction steps

1. Use an iPad or an iPhone and test the notification popup
2. ???
3. Profit

### 👍 Expected behavior

The notification popup should popup as well as the unread counter should show any number if there are notifications
![745F4F9A-1E21-48AB-893D-267B95B100CA](https://user-images.githubusercontent.com/40178814/185747357-02f5bb2f-3ead-4909-bd9f-f57dbef202c1.jpeg)

### 👎 Actual Behavior with Screenshots

https://user-images.githubusercontent.com/40178814/185747234-f5b2327e-6cae-414b-b3d3-2621e164606f.MOV

### 💻 Operating system

iOS 16 B4 and iPadOS 16 B3

### 🤖 Node Version

Latest Docker Image

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1250](https://linear.app/novu/issue/NV-1250/🐛-bug-report-no-counter-nor-any-popup-running-safari-browsers)</sub>

**Comment by jainpawan21** [comment] 2022-08-21 06:59
What is your URL?
http://localhost:4701/embed.umd.min.js or
https://embed.novu.co/embed.umd.min.js

I just tested with https://embed.novu.co/embed.umd.min.js
it is not reproducible for me.

**Comment by JustinBack** [comment] 2022-08-21 08:12
https://embed.novu.jrbit.de/embed.umd.min.js is the URL,

just tested with the `dev` images and its the same issue

**Comment by oba2311** [comment] 2022-08-22 08:03
@scopsy sounds like a good community issue to me.

**Comment by scopsy** [comment] 2022-08-22 12:50
@JustinBack just to verify something, is in any case you used Safari on the IOS machines? If it was Safari, @djabarovgeorge it might be related to what you have encountered with the safari tests you had.

**Comment by JustinBack** [comment] 2022-08-22 12:54
Yes on all iOS Devices and iPads I've used Safari

**Comment by scopsy** [comment] 2022-08-22 12:57
So it's defiently a Safari issue here, related to what @djabarovgeorge has encountered. Will update the title of the issue

**Comment by LetItRock** [comment] 2022-08-23 22:20
@scopsy hi, can I take this one? 
I was able to reproduce this issue. It seems like calling `postMessage` from the embed code is not working in Safari, I have a workaround for this but I'm looking for a better options ;)

**Comment by scopsy** [comment] 2022-08-24 06:48
@LetItRock Super curious to see the solution 🥹

**Comment by JustinBack** [comment] 2022-08-24 21:01
I‘d suggest to change the title to WebKit and not Safari as all Browsers are affected (Since all browsers run webkit in the background on iOS and iPadOS)

**Comment by LetItRock** [comment] 2022-08-28 22:48
@scopsy sorry for taking this that long... 

but when I've implemented the `postMessage` fix for Safari then I've noticed that it still doesn't work 😄 
so the real issue wasn't with `postMessage` but with the order of how JS/React code is executed in Chrome and Safari...
the call stacks are different 😮 

Chrome:
![Screenshot 2022-08-29 at 00 24 30](https://user-images.githubusercontent.com/2607232/187096996-ce79755c-6ccf-4e14-9181-5faeae814d4d.png)

Safari:
![Screenshot 2022-08-29 at 00 24 05](https://user-images.githubusercontent.com/2607232/187097004-8d12dda1-4ff8-4fd6-afd4-7aeb9d711625.png)

The easy way is to add the `setTimeout` over the `postMessage({ ..., INIT_IFRAME })` call in the `embed` and with a 100ms timeout it works well locally, but I don't recommend this because it might not work everywhere ex. on apps that have more code or which are on slower devices.

I think that we should reverse the messaging calls like: the `widget` should say to the `embed` when it's `ready` and only then `embed` should send the `INIT_IFRAME` event.

---

I've also found other issues:
- `embed` doesn't work on mobile devices because it's not listening to `touch` events --> easy to fix
- `widget` with notifications list is not positioned properly on mobile devices --> I haven't checked this one

---

**P.S.** 
> @LetItRock Super curious to see the solution 🥹

I've implemented this with a `localStorage` like you can listen to the `storage` events, then put the value and clean it right away 🤓 that's in short 😉

**Comment by JustinBack** [comment] 2022-08-29 03:38
Interesting! Correct me if I'm wrong, but can't you use Events?

https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events

Should make it easier and the code cleaner rather than using localStorage :-)

I haven't looked at the code at all though, so I'm not up to date if its feasible.

**Comment by scopsy** [comment] 2022-08-29 13:20
Thanks for the detailed writeup @LetItRock! I agree that the correct approach would be actually to reverse the order rather than a random timeout call. 

The implementation with localStorage is totally fine by me, ofcourse if there is other working and better suited API for this one this would be great as @JustinBack suggested. The problem with it from my quick glance is our ability to send those message across iframe boundaries.

**Comment by LetItRock** [comment] 2022-08-30 07:31
@scopsy @JustinBack 
The issue with the `DOM Events` is that you **can't** send them across **different domains** because of **CORS**.
In our case, the `embed` might be added to the domain "a" and the widget might be deployed on the domain "b".
That's why there is `postMessage` API.

I'll give a second try for the `postMessage` API, if it doesn't work then I'll go with a `localStorage` hack...

**Comment by scopsy** [comment] 2022-08-30 07:50
Yep, that was my thought on this too. @LetItRock sounds like a plan!

**Comment by JustinBack** [comment] 2022-09-06 16:08
I've just tested the fix on the dev branch and unfortunately it still won't open the iframe.

Due to a missing mac on my end I cannot export any console activity either, iDevices are pretty hard to debug without a mac...

Even with a cache clear, it does exactly the same as before the patch

**Comment by LetItRock** [comment] 2022-09-06 19:03
@JustinBack @scopsy 
From my quick look, I can see that the iframe with embed is there and it's reacting to the touch events, but the wrapper `novu-container` is not positioned properly on the mobile devices...

I've mentioned it before:
> widget with notifications list is not positioned properly on mobile devices --> I haven't checked this one

So the fix covered macOS Safari but did not fix the positioning issue on iOS...
I didn't have an iOS device at that time...

![Screenshot 2022-09-06 at 20 53 18](https://user-images.githubusercontent.com/2607232/188716984-3855be9b-4c3e-480b-9468-39c00f0b7fe1.png)
![301484542_1191149701443714_7352678135601370421_n](https://user-images.githubusercontent.com/2607232/188716993-20178632-ce2d-4627-a7a4-da2178d3ef60.jpeg)

**Comment by JustinBack** [comment] 2022-10-13 18:58
Just wanted to chime in quickly and say running the latest master build fixes the issue on iPadOS but not on iOS

![FE26336C-D8F5-404D-B602-2BA17B9E70E2](https://user-images.githubusercontent.com/40178814/195683522-8e56ba04-f77a-456f-855f-57e321c770d9.jpeg)

**Comment by oba2311** [comment] 2022-12-04 21:56
Can we close it?

**Closed** 2023-02-05 17:09 UTC
Labels: bug, good first issue, help wanted, linear
