### ISSUE TITLE
[NV-1721] 🐛 Bug Report: Issues at scale. Subscriber tab lagging

### ISSUE THREAD

**Issue by alaboudi** [novuhq/novu#2813] opened 2023-02-16 22:01 UTC
### 📜 Description

We have a lot of users in our business, in high 10s of millions, that we have hydrated into our self hosted Novu service / mongoDB. I have realized that the subscribers tab, in the lefthand side navigation, lags when clicked on at this scale

### 👟 Reproduction steps

1. Hydrate the Novu database with 50M+ users
2. Go to the subscribers tab 
3. Experience the 1 minute+ lag/crash 😆 

### 👍 Expected behavior

There should be no lag when visiting the subscribers tab

### 👎 Actual Behavior with Screenshots

<img width="1745" alt="image" src="https://user-images.githubusercontent.com/7456621/219496728-cd9a218a-9416-43cd-a2fe-ab0414c796ed.png">
Hangs like this for 5+ minutes

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

<sub>[NV-1721](https://linear.app/novu/issue/NV-1721/🐛-bug-report-issues-at-scale-subscriber-tab-lagging)</sub>

**Comment by davidsoderberg** [comment] 2023-02-17 06:44
test

**Comment by davidsoderberg** [comment] 2023-02-17 06:44
test

**Comment by scopsy** [comment] 2023-02-17 07:33
Related to #2099

**Comment by SebastianStehle** [comment] 2023-02-17 07:52
It is the count query. You need full index coverage here and I would add a dedicated collection for the count

**Comment by scopsy** [comment] 2023-02-17 07:57
@SebastianStehle what do you mean by a dedicated collection?

**Comment by SebastianStehle** [comment] 2023-02-17 08:54
Yes.

the problem is the size of the index. If it exceeds the memory limit you have to do calls to the disk again and I have never managed to get these queries really fast.

**Comment by scopsy** [comment] 2023-02-17 08:59
We can also limit the count for now, in case there are more than 100k (or any other) entries, just write: 100k+.

**Comment by SebastianStehle** [comment] 2023-02-17 09:21
How do you know that there are more than 100k without counting? ;)

**Comment by scopsy** [comment] 2023-02-20 07:46
@SebastianStehle from what I recall mongo have a `limit` property for `count` commands it will basically stop counting at the limit, and we can have the assumption if the count equals to the limit we can show `limit+` on the UI.

**Comment by oba2311** [comment] 2023-02-20 13:48
limit+ works IMO.

**Comment by alaboudi** [comment] 2023-02-21 18:16
oh I see. So this page also provides the total number of subscribers and that particular query is getting it to crash right, huh? on the same note as other here, there is a `limit()` parameter on the count query based on the [docs](https://www.mongodb.com/docs/manual/reference/method/db.collection.count/)

**Comment by SebastianStehle** [comment] 2023-02-21 23:23
@scopsy Sure, that works. But it is not the best usability. if you import 1 Mio users you want to know, if everything went fine. So if you show limit+ on the UI you should have at least an option to get the correct amount.

**Comment by alaboudi** [comment] 2023-02-21 23:55
@SebastianStehle is right. It may be best to capture this data in another table @scopsy to actually be able to get a figure for how many subscribers records you have in the DB. It would be a "projection" in a sense.

**Comment by alaboudi** [comment] 2023-02-21 23:57
Also a side note @scopsy. Based on the repo, I can see that you are using a CQRS architecture. If you consider something like Event Sourcing along with an Event Sourcing compatible database, you can get these projections almost for free. Just an FYI <3

**Comment by p-fernandez** [comment] 2023-06-15 13:03
@alaboudi have you tried our latest versions (v.014 onwards)? If so could you give us a bit of feedback?
We managed to fix some performance problems we had. It would be great news if you are not suffering those problems anymore.

**Comment by scopsy** [comment] 2023-07-31 15:20
@alaboudi we have done further updates to the pagination mechanism in 0.17.1 which have been identified as the root cause for the loading of this page. Please let me know if that still persists after that. Closing this issue for now 🙏

**Closed by scopsy** 2023-07-31 15:20 UTC
Labels: linear, triage

**Comment by alaboudi** [comment] 2023-07-31 18:32
Amazing thanks. We're versions behind but will update you when we upgrade
