### ISSUE TITLE
[NV-1891] 🐛 Bug Report:  /subscribers/me/preferences/0 gives a 500 error

### ISSUE THREAD

**Issue by vfxGer** [novuhq/novu#3064] opened 2023-03-21 17:26 UTC
### 📜 Description

/subscribers/{subscriberId}/preferences/0 gives a 500 error 

Logs:
```
 [Nest] 18  - 03/21/2023, 5:04:58 PM   ERROR [ExceptionsHandler] Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
     at new BSONTypeError (/usr/src/app/node_modules/.pnpm/bson@4.7.2/node_modules/bson/src/error.ts:16:5)
     at new ObjectId (/usr/src/app/node_modules/.pnpm/bson@4.7.2/node_modules/bson/src/objectid.ts:88:15)
     at /usr/src/app/libs/dal/dist/repositories/message/message.repository.js:188:32
     at Array.map (<anonymous>)
     at MessageRepository.<anonymous> (/usr/src/app/libs/dal/dist/repositories/message/message.repository.js:187:37)
     at Generator.next (<anonymous>)
     at /usr/src/app/libs/dal/dist/repositories/message/message.repository.js:8:71
     at new Promise (<anonymous>)
     at __awaiter (/usr/src/app/libs/dal/dist/repositories/message/message.repository.js:4:12)
     at MessageRepository.changeStatus (/usr/src/app/libs/dal/dist/repositories/message/message.repository.js:173:16)
     at MarkMessageAs.<anonymous> (/usr/src/app/apps/api/dist/webpack:/@novu/api/src/app/widgets/usecases/mark-message-as/mark-message-as.usecase.ts:27:34)
     at Generator.next (<anonymous>)
     at fulfilled (/usr/src/app/apps/api/dist/main.js:28205:58)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
When I pass in an appropriate index I get 500 too like
/subscribers/{subscriberId}/preferences/000000000000000000000001
Logs show
```
 [Nest] 18  - 03/21/2023, 5:21:52 PM   ERROR [ExceptionsHandler] Cannot read properties of null (reading 'steps')
 TypeError: Cannot read properties of null (reading 'steps')
     at GetSubscriberTemplatePreference.<anonymous> (/usr/src/app/apps/api/dist/webpack:/@novu/api/src/app/subscribers/usecases/get-subscriber-template-preference/get-subscriber-template-preference.usecase.ts:65:41)
     at Generator.next (<anonymous>)
     at /usr/src/app/apps/api/dist/main.js:23856:71
     at new Promise (<anonymous>)
     at __awaiter (/usr/src/app/apps/api/dist/main.js:23852:12)
     at GetSubscriberTemplatePreference.queryActiveChannels (/usr/src/app/apps/api/dist/main.js:23901:16)
     at GetSubscriberTemplatePreference.<anonymous> (/usr/src/app/apps/api/dist/webpack:/@novu/api/src/app/subscribers/usecases/get-subscriber-template-preference/get-subscriber-template-preference.usecase.ts:28:39)
     at Generator.next (<anonymous>)
     at /usr/src/app/apps/api/dist/main.js:23856:71
     at new Promise (<anonymous>)
     at __awaiter (/usr/src/app/apps/api/dist/main.js:23852:12)
     at GetSubscriberTemplatePreference.execute (/usr/src/app/apps/api/dist/main.js:23873:16)
     at UpdateSubscriberPreference.<anonymous> (/usr/src/app/apps/api/dist/webpack:/@novu/api/src/app/subscribers/usecases/update-subscriber-preference/update-subscriber-preference.usecase.ts:67:55)
     at Generator.next (<anonymous>)
     at fulfilled (/usr/src/app/apps/api/dist/main.js:26346:58)
     at runMicrotasks (<anonymous>)
```

### 👟 Reproduction steps

curl PATCH {base url}/subscribers/{subscriberId}/preferences/0
curl PATCH {base url}/subscribers/{subscriberId}/preferences/000000000000000000000001

### 👍 Expected behavior

Get 404

### 👎 Actual Behavior with Screenshots

Got 500 errros

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

<sub>[NV-1891](https://linear.app/novu/issue/NV-1891/🐛-bug-report-subscribersmepreferences0-gives-a-500-error)</sub>

**Comment by jainpawan21** [comment] 2023-03-22 04:23
Hi @vfxGer 
Thanks for this issue.
We are not validating templateId in params. It is of type string. 
We can do something like this to validate.
https://www.appsloveworld.com/mongodb/100/172/nestjs-validate-param-format-of-mongo-objectid

Let me know if you are interested to work on this!

**Comment by gitstart** [comment] 2023-04-10 12:48
Hello @jainpawan21 sorry for the delay on this. 

We are unable to reproduce this issue. Here are some screenshots from our manual testing for the use cases highlighted above.
![Screenshot 2023-04-10 at 2 23 56 PM](https://user-images.githubusercontent.com/1501599/230904269-e362f744-f44c-4d97-a7ca-28a79bd224a2.png)
![Screenshot 2023-04-10 at 1 56 55 PM](https://user-images.githubusercontent.com/1501599/230904282-97f5965c-f055-4a39-b7d2-1d2ea842b79e.png)
![Screenshot 2023-04-10 at 1 56 31 PM](https://user-images.githubusercontent.com/1501599/230904288-b291ffa1-a139-44e3-a18e-0f8462de1ad0.png)

**Comment by p-fernandez** [comment] 2023-06-15 12:54
Closing as not reproducible. @vfxGer feel free to open it again if it continues to happen to you in the latest versions.

**Closed** 2023-06-21 04:41 UTC
Labels: help wanted, linear
